### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gaoagong** [aws-observability/aws-otel-collector#2079]
Some of our AWS CF Templates weren't specifying a hardcoded version of the aws-collector and after yesterday, we have started seeing the error:

panic: runtime error: invalid memory address or nil pointer dereference

and subsequently:

otel.javaagent 2023-05-16 19:24:04:379 +0000] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317

This was a version change from v0.28.0 to v0.29.0

This actually brings down our Fargate hosted ECS tasks, or at least it seems to be. I'm still researching the exact reason. I just know that the errors above are the last thing we see on the task before it dies.

I'm going to hardcode the old version in our CF Template and see if it fixes the issue.

**Comment by nbrigand-sloclap** [comment]
Hi!
Same problem here. Here is the callstack we get:
`
panic: runtime error: invalid memory address or nil pointer dereference	bc674eeebef94faaac56a90efb430a95	OTELCollectorSidecar
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x133ce28]	bc674eeebef94faaac56a90efb430a95	OTELCollectorSidecar
goroutine 76 [running]:	bc674eeebef94faaac56a90efb430a95	OTELCollectorSidecar
go.opentelemetry.io/collector/pdata/pcommon.Slice.Len(...)
go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/pcommon/slice.go:52
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/internal/translator.makeAws(0x4a9516a740f06464?, {0xc0009d7f50?}, {0x0, 0x0, 0x0?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.76.3/internal/translator/aws.go:171 +0xac8
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/internal/translator.MakeSegment({0x37c7ea0?}, {0xc0009d7950?}, {0xc000275800, 0x8, 0x8}, 0x0?, {0x0, 0x0, 0x0})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.76.3/internal/translator/segment.go:110 +0x20b
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/internal/translator.MakeSegmentDocumentString({0x416530?}, {0xc000635800?}, {0xc000275800?, 0xc0007e5210?, 0x40e507?}, 0x70?, {0x0?, 0xc0007e5108?, 0xc0007e5370?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.76.3/internal/translator/segment.go:71 +0x2d
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter.extractResourceSpans({0x36968e0?, 0xc0003ae500}, 0x4b41fd8?, {0xc000810300?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.76.3/awsxray.go:119 +0x1df
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter.newTracesExporter.func1({0x12a05f200?, 0x6cc5640?}, {0x12a05f200?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.76.3/awsxray.go:70 +0x24d
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).Export(0x4b5e2e0?, {0x4b5e2a8?, 0xc0009d7ef0?})
go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/traces.go:70 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc0008d9990, {0x4b6fa90, 0xc0009d7e90})
go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/common.go:208 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc0008a86e0, {0x4b6fa90?, 0xc0009d7e90?})
go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:365 +0x190
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send(0xc0009aeff0, {0x4b6fa90, 0xc0009d7e90})
go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/traces.go:137 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send(0xc000802380, {0x4b6fa90, 0xc0009d7e90})
go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/queued_retry.go:301 +0x44c
go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesExporter.func2({0x4b5e2e0?, 0xc0009d6e10}, {0xc0009af680?})
go.opentelemetry.io/collector/exporter@v0.76.1/exporterhelper/traces.go:116 +0xca
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces(...)
go.opentelemetry.io/collector/consumer@v0.76.1/traces.go:36
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export(0xc0009d6db0, {0x4b5e2e0, 0xc0009d6e10}, 0x2?, 0x0)
go.opentelemetry.io/collector/processor/batchprocessor@v0.76.1/batch_processor.go:270 +0x117
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems(0xc0009b88c0, 0xc000092f3c?)
go.opentelemetry.io/collector/processor/batchprocessor@v0.76.1/batch_processor.go:188 +0x5c
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle(0xc0009b88c0)
go.opentelemetry.io/collector/processor/batchprocessor@v0.76.1/batch_processor.go:150 +0x1b6
created by go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).Start
go.opentelemetry.io/collector/processor/batchprocessor@v0.76.1/batch_processor.go:101 +0x6a
`

**Comment by nikoremi97** [comment]
Same here. We started to receive errors in our containers related to ADOT in our container (not the aws-otel-collector)

`2023/05/16 12:45:17 traces export: max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:4317: connect: connection refused"`

we ended up to removing this line from our OTEL config `"command": ["--config=/etc/ecs/container-insights/otel-task-metrics-config.yaml"]`

**Comment by dcu** [comment]
sadly we were affected as well

**Comment by denisgotthans** [comment]
Same here.
I find out that this problem occurs if I enable the **aws xray exporter** and if we have some load.

We are running our collector as service on ecs fargate. We use CDK for infrastructure as code.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14631c8]
goroutine 96 [running]:
go.opentelemetry.io/collector/pdata/pcommon.Slice.Len(...)
go.opentelemetry.io/collector/pdata@v1.0.0-rcv0011/pcommon/slice.go:52
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/internal/translator.makeAws(0x84a28c18d9566c64?, {0xc005be5d10?}, {0x0, 0x0, 0x19?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.77.0/internal/translator/aws.go:171 +0xac8
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/internal/translator.MakeSegment({0x5b24560?}, {0xc001699200?}, {0x0, 0x0, 0x0}, 0x0?, {0x0, 0x0, 0x0})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.77.0/internal/translator/segment.go:110 +0x20b
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter/internal/translator.MakeSegmentDocumentString({0x4165f0?}, {0xc0058102b8?}, {0x0?, 0xc0052911a8?, 0x414cc5?}, 0xa8?, {0x0?, 0xffffffffffffffff?, 0x20?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.77.0/internal/translator/segment.go:71 +0x2d
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter.extractResourceSpans({0x58f1620?, 0xc000b38e00}, 0xc005291448?, {0xc00066e840?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.77.0/awsxray.go:119 +0x1df
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter.newTracesExporter.func1({0x12a05f200?, 0xbd79fc0?}, {0x12a05f200?})
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/awsxrayexporter@v0.77.0/awsxray.go:70 +0x24d
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesRequest).Export(0x7be5818?, {0x7be57e0?, 0xc005826660?})
go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/traces.go:70 +0x34
go.opentelemetry.io/collector/exporter/exporterhelper.(*timeoutSender).send(0xc000bcc368, {0x7c06258, 0xc005826600})
go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/common.go:208 +0x96
go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send(0xc000a1bc20, {0x7c06258?, 0xc005826600?})
go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/queued_retry.go:366 +0x190
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send(0xc000a7d938, {0x7c06258, 0xc005826600})
go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/traces.go:137 +0x88
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send(0xc000844700, {0x7c06258, 0xc005826600})
go.opentelemetry.io/collector/exporter@v0.77.0/exporterhelper/queued_retry.go:302 +0x44c

```

**Comment by Aneurysm9** [comment]
We have identified the cause of this failure.  https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/22707 has been created to address this upstream.

**Comment by denisgotthans** [comment]
Thank you, it now works with version 0.78.0 of the opentelemetry-collector-contrib.

**Comment by Aneurysm9** [comment]
> Thank you, it now works with version 0.78.0 of the opentelemetry-collector-contrib.

Excellent! Thanks for the confirmation. I'm very glad we were able to get the fix in under the wire for that release. We are preparing a `v0.29.1` release of the ADOT collector to include this fix.

**Comment by Aneurysm9** [comment]
This issue has been fixed in the [`v0.29.1` release](https://github.com/aws-observability/aws-otel-collector/releases/tag/v0.29.1).
