### ISSUE TITLE
Connection Refused running otel agent in EC2

### ISSUE THREAD

**Issue by studentaws01** [aws-observability/aws-otel-collector#345]
Hello aws otel community,
I am trying opentelemetry on my EC2 for the first time and am following this [tutorial](https://www.youtube.com/watch?v=837NtV0McOA) but I keep getting this error

`[opentelemetry.auto.trace 2021-02-05 22:15:33:217 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporter.otlp.OtlpGrpcMetricExporter - Failed to export metrics
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: 

Connection refused: localhost/127.0.0.1:4317

Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
        at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)`

I have tried running the collector via [docker](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/docker-demo.md) 

and also using[EC2](https://github.com/aws-observability/aws-otel-collector/blob/main/docs/developers/linux-rpm-demo.md) installation but no luck.

The collector process runs and seems to be ok.  I see this in the logs
`2021-02-05 22:11:24.791973929 +0000 UTC m=+0.089273139, Level:info, Caller:go.opentelemetry.io/collector@v0.19.0/service/service.go:267, Message:Everything is ready. Begin running and processing data., Stack:}`

Here is the command that I use to run the spring boot app
`java -javaagent:/home/ssm-user/aws-opentelemetry-agent.jar -Dotel.exporter=otlp -Dotel.resource.attributes=service.name=MyTest -jar spring-petclinic-2.4.2.jar`

Any help to get this working would be much appreciated.

[otel discussion forum](https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2208) suggested I ask here.  Thanks

**Comment by mxiamxia** [comment]
Hi @studentaws01 , the latest `auto-java-instrumentation-agent` has updated the default `grpc` port to `4317` but the OTel collector default port is still `55680`. Can you edit the collector config file under `/opt/aws/aws-otel-collector/etc/config.yaml` and change the OTLP Receiver GRPC port to `4317` on your EC2?

We'll update OTEL OTLP GRPC port to `4317` in the default config in the next release. thanks.

**Comment by studentaws01** [comment]
Thanks.. I was able to run using -Dotel.exporter.otlp.endpoint=127.0.0.1:55680 with aws-opentelemetry-agent.jar.  However, now I am hitting this next error
<pre>
`2021-02-08 20:39:02.420371852 +0000 UTC m=+0.059079853, Level:info, Caller:go.opentelemetry.io/collector@v0.19.0/service/builder/receivers_builder.go:75, Message:Receiver started., Stack:}
{2021-02-08 20:39:02.420388872 +0000 UTC m=+0.059096827, Level:info, Caller:github.com/jaegertracing/jaeger@v1.21.0/pkg/healthcheck/handler.go:128, Message:Health Check state change, Stack:}
{2021-02-08 20:39:02.420404633 +0000 UTC m=+0.059112638, Level:info, Caller:go.opentelemetry.io/collector@v0.19.0/service/service.go:267, Message:Everything is ready. Begin running and processing data., Stack:}
{2021-02-08 20:39:47.457193113 +0000 UTC m=+45.095901341, Level:error, Caller:go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/queued_retry.go:204, Message:Exporting failed. Try enabling retry_on_failure config option., Stack:go.opentelemetry.io/collector/exporter/exporterhelper.(*retrySender).send
        go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/queued_retry.go:204
go.opentelemetry.io/collector/exporter/exporterhelper.(*tracesExporterWithObservability).send
        go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/tracehelper.go:114
go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
        go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/queued_retry.go:140
go.opentelemetry.io/collector/exporter/exporterhelper.(*traceExporter).ConsumeTraces
        go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/tracehelper.go:68
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:251
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:186
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).processItem
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:168
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:141}
{2021-02-08 20:39:47.457337337 +0000 UTC m=+45.096045325, Level:error, Caller:go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/queued_retry.go:142, Message:Exporting failed. Dropping data. Try enabling sending_queue to survive temporary failures., Stack:go.opentelemetry.io/collector/exporter/exporterhelper.(*queuedRetrySender).send
        go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/queued_retry.go:142
go.opentelemetry.io/collector/exporter/exporterhelper.(*traceExporter).ConsumeTraces
        go.opentelemetry.io/collector@v0.19.0/exporter/exporterhelper/tracehelper.go:68
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:251
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).sendItems
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:186
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).processItem
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:168
go.opentelemetry.io/collector/processor/batchprocessor.(*batchProcessor).startProcessingCycle
        go.opentelemetry.io/collector@v0.19.0/processor/batchprocessor/batch_processor.go:141}
`
</pre>
I am using the config.yaml as shown [here](https://raw.githubusercontent.com/aws-observability/aws-otel-collector/main/config.yaml)

Is there another example of config.yaml that works with XRay.  

Thanks

**Comment by mxiamxia** [comment]
It looks the permission issue. Can you attach the following permissions to your EC2 host where the collector is running?

https://aws-otel.github.io/docs/setup/permissions

**Comment by mxiamxia** [comment]
The new release has changed the default port to `4317`. Close the issue.
