### ISSUE TITLE
Failure to Connect Causes Fail on Application Startup

### ISSUE THREAD

**Issue by dentonmwood** [aws-observability/aws-otel-collector#539]
We're using the OpenTelemetry collector with a Java Spring app running as an ECS Fargate task. When we first released an update to our site after go-live the other day, we had a weird issue where the OTEL JAR bundled with the Spring app could not connect to the collector at localhost:4317 (I think). This caused the application to fail. Are there any configuration settings for not having the application fail if OTEL fails? And/or is there any reason why this would happen? The sidecar container came up correctly and appeared to be ready to receive requests per the logs.

**Comment by anuraaga** [comment]
Hi @dentonmwood - to confirm it sounds like you are not using the OTel java agent based on "JAR bundled with the Spring app". Does it mean you're using spring-cloud-sleuth? Exports generally happen in a background thread and would not cause an app to fail, but there could be a misconfiguration - if using spring-cloud-sleuth, it seems you need to include `opentelemetry-api-metrics` in your app yourself or you use the `SimpleSpanProcessor` which exports on the app thread which will be bad for performance and may cause failures

https://github.com/spring-cloud-incubator/spring-cloud-sleuth-otel/blob/main/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/OtelAutoConfiguration.java#L105

**Comment by dentonmwood** [comment]
@anuraaga We're actually using the OTEL Agent JAR provided here (https://aws-otel.github.io/docs/getting-started/java-sdk/trace-auto-instr). The Docker image copies the JAR from our code repository into the container and initializes the attributes:

```
# Install the AWS OTEL auto-instrumentor
COPY docker/aws/otel/aws-opentelemetry-agent.jar docker/aws/aws-opentelemetry-agent.jar
ENV JAVA_TOOL_OPTIONS="-javaagent:$WORKDIR/docker/aws/aws-opentelemetry-agent.jar"
ENV OTEL_RESOURCE_ATTRIBUTES="service.name=contest,service.namespace=contest"
```

We don't have any code related to OTEL - it's entirely separate from the Spring app and only installed via the Docker build.

**Comment by dentonmwood** [comment]
Just to note, this is working fine for us right now. We can see and navigate traces in X-Ray, which is the primary reason we installed OTEL. I just want to make sure it doesn't cause our app to fail if it doesn't work on startup.

**Comment by anuraaga** [comment]
In that case, we definitely don't expect a failure to connect to the collector to affect the app, the agent sets up the processor to export in the background. Can you describe the failure more? Perhaps ECS was set up to healthcheck the collector which failed, but not the app?

**Comment by dentonmwood** [comment]
@anuraaga Was just able to replicate the issue. The ECS task is composed of 2 containers: our application container and the OTEL container. Only the application container is deemed essential for the task. Here's the CloudFormation config for the OTEL container:

```
Name: "aws-otel-collector"
Image: "amazon/aws-otel-collector"
Command:
  - "--config=/etc/ecs/ecs-default-config.yaml"
Essential: false
LogConfiguration:
  LogDriver: "awslogs"
  Options:
    awslogs-group: !Ref OpenTelemetryCollectorLogsGroup
    awslogs-region: !Sub "${AWS::Region}"
    awslogs-stream-prefix: "ecs"
```

and here's the CloudFormation config for the application container (minus environment variables, secrets, and the image definition):

```
Name: "icpc-application"
Essential: true
LogConfiguration:
  LogDriver: "awslogs"
  Options:
    awslogs-group: !Ref IcpcApplicationLogsGroup
    awslogs-region: !Sub "${AWS::Region}"
    awslogs-stream-prefix: "ecs"
PortMappings:
  - ContainerPort: !Ref ServicePort
    HostPort: !Ref ServicePort
    Protocol: "tcp"
```

The OTEL container appears to start successfully:
```
2021-06-11T22:08:30.339Z	info	builder/receivers_builder.go:70	Receiver is starting...	{     "kind": "receiver",     "name": "otlp" }
--
2021-06-11T22:08:30.339Z	info	otlpreceiver/otlp.go:83	Starting GRPC server on endpoint 0.0.0.0:4317	{     "kind": "receiver",     "name": "otlp" }
2021-06-11T22:08:30.340Z	info	otlpreceiver/otlp.go:145	Setting up a second GRPC listener on legacy endpoint 0.0.0.0:55680	{     "kind": "receiver",     "name": "otlp" }
2021-06-11T22:08:30.340Z	info	otlpreceiver/otlp.go:83	Starting GRPC server on endpoint 0.0.0.0:55680	{     "kind": "receiver",     "name": "otlp" }
2021-06-11T22:08:30.340Z	info	otlpreceiver/otlp.go:101	Starting HTTP server on endpoint 0.0.0.0:55681	{     "kind": "receiver",     "name": "otlp" }
2021-06-11T22:08:30.340Z	info	builder/receivers_builder.go:75	Receiver started.	{     "kind": "receiver",     "name": "otlp" }
2021-06-11T22:08:30.340Z	info	healthcheck/handler.go:128	Health Check state change	{     "kind": "extension",     "name": "health_check",     "status": "ready" }
2021-06-11T22:08:30.340Z	info	service/application.go:197	Everything is ready. Begin running and processing data.
```

However, we see these logs in the application container:

```

[opentelemetry.auto.trace 2021-06-11 22:15:36:843 +0000] [grpc-default-executor-0] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics
--
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at io.grpc.Status.asRuntimeException(Status.java:533)
at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:4317
Caused by: java.net.ConnectException: Connection refused
at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)


```

**Comment by dentonmwood** [comment]
Other notes:
* The application fails after the above log entries are logged.
* I'm not sure what version of the OTEL JAR we're using - I had to download it last fall because our Docker build runs inside an internet-locked environment. I can try updating to the latest version and reporting if we have a problem again.

**Comment by dentonmwood** [comment]
Update 2: Tried to update to latest published JAR (v.1.2.0) and got the following in the application logs:
```
[opentelemetry.auto.trace 2021-06-11 23:12:10:233 +0000] [grpc-default-executor-3] ERROR io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network.UNAVAILABLE: io exception
```

**Comment by anuraaga** [comment]
Is your collector also the latest version? Been a while since last fall and since metrics aren't stable I think there were some breaking changes since that affecting compatibility.

It would be nice if you can check with the latest versions since it has been a while since then.

**Comment by dentonmwood** [comment]
We don't specify a version with the collector image, so I assume it's pulling the latest image. Tried with latest JAR - see results above.

**Comment by dentonmwood** [comment]
@anuraaga any updates? I've tried with the latest version on both and have still experienced this issue. It's not consistent but it does happen.

**Comment by anuraaga** [comment]
@dentonmwood Just want to confirm the versions, the first line outputed by the collector should be a version number and the java agent also outputs the version in its logs. Can you make sure they're both the latest?

@mxiamxia Can you think of any reason the container would exit if the collector isn't reachable? I can't think of any reason for the Java side to be affected by it since it's just a background thread.

**Comment by mxiamxia** [comment]
In the latest version of JAR (w/ the latest OTel Java SDK), it requires OTLP endpoint has the prefix `http://`. Could you make sure that you're using the latest ADOT collector image and AWS-Auto-Instr-Agent JAR, And then set the following environment var for your App in the ECS task definition. I also can't think of any reason App could be failed & exit if the collector is not reachable. How did you find the App was exit? Do you see your App container process keep rebooting in ECS console? or just the repeating error logs - `io.grpc.StatusRuntimeException: UNAVAILABLE: io exception`?

```
      "environment": [
        {
          "name": "OTEL_OTLP_ENDPOINT",
          "value": "http://localhost:4317"
        },
```

cc @dentonmwood , @anuraaga

**Comment by dentonmwood** [comment]
Update: while we were occasionally seeing in the logs that OTEL had failed, the app itself was failing due to an entirely different issue that we resolved. Thank y'all for your help and kind responses.
