### ISSUE TITLE
opentelemetry.auto.trace : WARN io.opentelemetry.javaagent.instrumentation.tomcat.common.TomcatTracer - Malformed url? scheme: http, host: null, port: 8900, path: null, query: null

### ISSUE THREAD

**Issue by georges-git** [aws-observability/aws-otel-collector#578]
Hello @mxiamxia and AWS team - Getting following error , how to resolve it?

2021-07-08T14:22:34.424-05:00	[opentelemetry.auto.trace 2021-07-08 15:22:34:423 -0400] [http-nio-8900-exec-22] WARN io.opentelemetry.javaagent.instrumentation.tomcat.common.TomcatTracer - Malformed url? scheme: http, host: null, port: 8900, path: null, query: null
2021-07-08T14:22:34.424-05:00	java.net.URISyntaxException: Expected scheme-specific part at index 5: http:
2021-07-08T14:22:34.424-05:00	at java.base/java.net.URI$Parser.fail(URI.java:2913)
2021-07-08T14:22:34.424-05:00	at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
2021-07-08T14:22:34.424-05:00	at java.base/java.net.URI$Parser.parse(URI.java:3119)
2021-07-08T14:22:34.424-05:00	at java.base/java.net.URI.<init>(URI.java:685)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.instrumentation.tomcat.common.TomcatTracer.url(TomcatTracer.java:82)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.instrumentation.tomcat.common.TomcatTracer.url(TomcatTracer.java:29)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.shaded.instrumentation.api.tracer.HttpServerTracer.setUrl(HttpServerTracer.java:189)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.shaded.instrumentation.api.tracer.HttpServerTracer.onRequest(HttpServerTracer.java:172)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.shaded.instrumentation.api.tracer.HttpServerTracer.startSpan(HttpServerTracer.java:81)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.shaded.instrumentation.api.tracer.HttpServerTracer.startSpan(HttpServerTracer.java:57)
2021-07-08T14:22:34.424-05:00	at io.opentelemetry.javaagent.instrumentation.tomcat.common.TomcatTracer.startServerSpan(TomcatTracer.java:35)

**Comment by mxiamxia** [comment]
Hi @georges-git , can you share which version of `javaagent` your service is using? It looks `host` value is missing in URL the agent is trying to intercept. I'll forward this issue to OTel community for the help.

**Comment by georges-git** [comment]
Hello @mxiamxia  - Here is the java agent version i am using: https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar.

Is this ok?
