### ISSUE TITLE
Collector container showing error about unable to resolve host or service. 

### ISSUE THREAD

**Issue by rathorens** [aws-observability/aws-otel-collector#585]
[opentelemetry.auto.trace 2021-07-21 03:15:03:532 +0000] [main] INFO io.opentelemetry.javaagent.tooling.TracerInstaller - Installed span exporter: io.opentelemetry.exporter.otlp.OtlpGrpcSpanExporter
[opentelemetry.auto.trace 2021-07-21 03:15:03:547 +0000] [main] INFO io.opentelemetry.javaagent.tooling.TracerInstaller - Installed metric exporter: io.opentelemetry.exporter.otlp.OtlpGrpcMetricExporter
[opentelemetry.auto.trace 2021-07-21 03:15:03:572 +0000] [main] INFO io.opentelemetry.javaagent.tooling.PropagatorsInitializer - Added xray propagator
[opentelemetry.auto.trace 2021-07-21 03:15:03:572 +0000] [main] INFO io.opentelemetry.javaagent.tooling.PropagatorsInitializer - Added tracecontext propagator
[opentelemetry.auto.trace 2021-07-21 03:15:03:572 +0000] [main] INFO io.opentelemetry.javaagent.tooling.PropagatorsInitializer - Added b3 propagator
[opentelemetry.auto.trace 2021-07-21 03:15:03:572 +0000] [main] INFO io.opentelemetry.javaagent.tooling.PropagatorsInitializer - Added b3multi propagator
[opentelemetry.auto.trace 2021-07-21 03:15:03:587 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.12.1-aws.1
**SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".**
**SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[opentelemetry.auto.trace 2021-07-21 03:15:04:822 +0000] [grpc-default-executor-0] WARN io.grpc.internal.ManagedChannelImpl - [Channel<3>: (aws-ot-collector:4317)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host aws-ot-collector, cause=java.lang.RuntimeException: java.net.UnknownHostException: aws-ot-collector: Name or service not known**
	at io.grpc.internal.DnsNameResolver.resolveAddresses(DnsNameResolver.java:223)
	at io.grpc.internal.DnsNameResolver.doResolve(DnsNameResolver.java:282)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:318)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.UnknownHostException: aws-ot-collector: Name or service not known

**Comment by rathorens** [comment]
Further logs:

The collector container is failing to start with below error:

021-07-21T02:57:32.059Z	info	service/collector.go:262	Starting aws-otel-collector...	{"Version": "v0.11.0", "NumCPU": 4}
2021-07-21T02:57:32.059Z	info	service/collector.go:170	Setting up own telemetry...
2021-07-21T02:57:32.063Z	info	service/telemetry.go:99	Serving Prometheus metrics	{"address": ":8888", "level": 0, "service.instance.id": "e1f68641-b569-46c6-b443-4cd74cd6b874"}
2021-07-21T02:57:32.063Z	info	service/collector.go:205	Loading configuration...
Error: cannot load configuration's parser: error loading config file "/etc/otel-agent-config.yaml": unable to read the file /etc/otel-agent-config.yaml: read /etc/otel-agent-config.yaml: is a directory
2021/07/21 02:57:32 application run finished with error: cannot load configuration's parser: error loading config file "/etc/otel-agent-config.yaml": unable to read the file /etc/otel-agent-config.yaml: read /etc/otel-agent-config.yaml: is a directory
2021/07/21 03:14:57 AWS OTel Collector version: v0.11.0
2021/07/21 03:14:57 find no extra config, skip it, err: open /opt/aws/aws-otel-collector/etc/extracfg.txt: no such file or directory
2021-07-21T03:14:57.209Z	info	service/collector.go:262	Starting aws-otel-collector...	{"Version": "v0.11.0", "NumCPU": 4}
2021-07-21T03:14:57.209Z	info	service/collector.go:170	Setting up own telemetry...
2021-07-21T03:14:57.212Z	info	service/telemetry.go:99	Serving Prometheus metrics	{"address": ":8888", "level": 0, "service.instance.id": "b2896769-2d86-4233-9a55-48fda529fcbe"}
2021-07-21T03:14:57.212Z	info	service/collector.go:205	Loading configuration...
Error: cannot load configuration's parser: error loading config file "/etc/otel-agent-config.yaml": unable to read the file /etc/otel-agent-config.yaml: read /etc/otel-agent-config.yaml: is a directory
2021/07/21 03:14:57 application run finished with error: cannot load configuration's parser: error loading config file "/etc/otel-agent-config.yaml": unable to read the file /etc/otel-agent-config.yaml: read /etc/otel-agent-config.yaml: is a directory

Where do I need to put this file /etc/otel-agent-config.yaml?
